---
- name: create interface test
  hosts: routers
  become: yes

  tasks:
    - name: Create Loopback66
      cisco.ios.ios_interfaces:
        config:
        - name: Loopback66
          description: Created by Ansible Test
          enabled: true

          
    - name: Add IP Addredd to Loopback66
      cisco.ios.ios_l3_interfaces:
        config:
        - name: GigabitEthernet0/1
          ipv4:
          - address: 192.168.66.66/32