---
datacenter:
  children:
    routers:
      hosts:
        sandbox-iosxe-latest-1.cisco.com:
  vars:
    ansible_connection: network_cli
    ansible_network_os: ios
    ansible_user: developer
    ansible_ssh_pass: C1sco12345